import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";
import { getNickname } from "@/utils/generateNickname";

const inter = Inter({ subsets: ["latin"] });

type Message = {
  nickname: string;
  text: string;
};

export default function Home() {
  const socketRef = React.useRef<WebSocket>();
  const chatSendInputRef = React.useRef<HTMLInputElement>(null);
  const [nickname, setNickname] = React.useState<string>("");
  const [chatList, setChatList] = React.useState<Message[]>([]);

  React.useEffect(() => {
    socketRef.current = new WebSocket("ws://localhost:8080");
    if (!socketRef.current) return;
    const socket = socketRef.current;
    socket.addEventListener("open", (event) => {
      const nickname = getNickname();
      setNickname(nickname);
      const userJoinData = JSON.stringify({
        type: "userJoin",
        nickname: nickname,
      });
      console.log("WebSocket connected");
      socket.send(userJoinData);
    });

    socket.addEventListener("message", (event) => {
      const message: Message = JSON.parse(event.data);
      setChatList((prev) => [...prev, message]);

      console.log("Received message:", event.data);
      // setSocketMessage(event.data);
    });

    socket.addEventListener("close", (event) => {
      console.log("WebSocket closed:", event);
    });

    socket.addEventListener("error", (event) => {
      console.log("WebSocket error:", event);
    });

    window.addEventListener("beforeunload", () => {
      socket.close();
    });

    if (chatSendInputRef.current) chatSendInputRef.current.focus();
  }, []);

  const handleChatSend = (e: React.FormEvent) => {
    e.preventDefault();
    if (!socketRef.current) return;
    const socket = socketRef.current;
    const chatSendInput = chatSendInputRef.current;
    if (!chatSendInput) return;
    const chat = chatSendInput.value;
    socket.send(chat);
    //send Chat to server;
    // do something...
    //send Chat to server;
    if (!chat) return;
    chatSendInput.value = "";
  };
  console.log(
    nickname,
    chatList.filter((chat) => {
      console.log(chat.nickname);
    })
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Chat</h1>
        <h1>{nickname}님 안녕하세요!</h1>
        <section className={styles.chatSection}>
          <div className={styles.chatList}>
            <div className={styles.myChatList}>
              {chatList
                .filter((chat) => chat.nickname === nickname)
                .map((chat, index) => {
                  return (
                    <div key={index} className={styles.myChat}>
                      <span>{chat.nickname}: </span>
                      <span>{chat.text}</span>
                    </div>
                  );
                })}
            </div>
            <div className={styles.otherChatList}>
              {chatList
                .filter((chat) => chat.nickname !== nickname)
                .map((chat, index) => {
                  return (
                    <div key={index} className={styles.otherChat}>
                      <span>{chat.nickname}: </span>
                      <span>{chat.text}</span>
                    </div>
                  );
                })}
            </div>
          </div>

          <form className={styles.chatSender} onSubmit={handleChatSend}>
            <input type="text" ref={chatSendInputRef} autoFocus />
            <button type="submit">Send</button>
          </form>
        </section>
      </main>
    </>
  );
}
